package com.yszt.base.model.generator;

import com.yszt.base.BaseModel;

@SuppressWarnings("serial")
public class AppVersions extends BaseModel {
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appVersions.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appVersions.appName
     *
     * @mbggenerated
     */
    private String appname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appVersions.upload_location
     *
     * @mbggenerated
     */
    private String uploadLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appVersions.version_number
     *
     * @mbggenerated
     */
    private String versionNumber;

    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appVersions.version
     *
     * @return the value of appVersions.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appVersions.version
     *
     * @param version the value for appVersions.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appVersions.appName
     *
     * @return the value of appVersions.appName
     *
     * @mbggenerated
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appVersions.appName
     *
     * @param appname the value for appVersions.appName
     *
     * @mbggenerated
     */
    public void setAppname(String appname) {
        this.appname = appname == null ? null : appname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appVersions.upload_location
     *
     * @return the value of appVersions.upload_location
     *
     * @mbggenerated
     */
    public String getUploadLocation() {
        return uploadLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appVersions.upload_location
     *
     * @param uploadLocation the value for appVersions.upload_location
     *
     * @mbggenerated
     */
    public void setUploadLocation(String uploadLocation) {
        this.uploadLocation = uploadLocation == null ? null : uploadLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appVersions.version_number
     *
     * @return the value of appVersions.version_number
     *
     * @mbggenerated
     */
    public String getVersionNumber() {
        return versionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appVersions.version_number
     *
     * @param versionNumber the value for appVersions.version_number
     *
     * @mbggenerated
     */
    public void setVersionNumber(String versionNumber) {
        this.versionNumber = versionNumber == null ? null : versionNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appVersions
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", version=").append(version);
        sb.append(", appname=").append(appname);
        sb.append(", uploadLocation=").append(uploadLocation);
        sb.append(", versionNumber=").append(versionNumber);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appVersions
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AppVersions other = (AppVersions) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getEnable() == null ? other.getEnable() == null : this.getEnable().equals(other.getEnable()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getAppname() == null ? other.getAppname() == null : this.getAppname().equals(other.getAppname()))
            && (this.getUploadLocation() == null ? other.getUploadLocation() == null : this.getUploadLocation().equals(other.getUploadLocation()))
            && (this.getVersionNumber() == null ? other.getVersionNumber() == null : this.getVersionNumber().equals(other.getVersionNumber()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appVersions
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getEnable() == null) ? 0 : getEnable().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getAppname() == null) ? 0 : getAppname().hashCode());
        result = prime * result + ((getUploadLocation() == null) ? 0 : getUploadLocation().hashCode());
        result = prime * result + ((getVersionNumber() == null) ? 0 : getVersionNumber().hashCode());
        return result;
    }
}