package com.yszt.base.model.generator;

import java.io.Serializable;
import java.util.Date;

import com.yszt.base.BaseModel;

@SuppressWarnings("serial")
public class DiaryStandard extends BaseModel implements Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diary_standard.diary_code
	 * @mbggenerated
	 */
	private String diaryCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diary_standard.ori_text_id
	 * @mbggenerated
	 */
	private Integer oriTextId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diary_standard.diary_date
	 * @mbggenerated
	 */
	private Date diaryDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diary_standard.start_time
	 * @mbggenerated
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diary_standard.end_time
	 * @mbggenerated
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diary_standard.action_addr
	 * @mbggenerated
	 */
	private String actionAddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diary_standard.action_state
	 * @mbggenerated
	 */
	private String actionState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diary_standard.weather
	 * @mbggenerated
	 */
	private String weather;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diary_standard.emotion
	 * @mbggenerated
	 */
	private String emotion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column diary_standard.audio_location
	 * @mbggenerated
	 */
	private String audioLocation;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diary_standard.diary_code
	 * @return  the value of diary_standard.diary_code
	 * @mbggenerated
	 */
	public String getDiaryCode() {
		return diaryCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diary_standard.diary_code
	 * @param diaryCode  the value for diary_standard.diary_code
	 * @mbggenerated
	 */
	public void setDiaryCode(String diaryCode) {
		this.diaryCode = diaryCode == null ? null : diaryCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diary_standard.ori_text_id
	 * @return  the value of diary_standard.ori_text_id
	 * @mbggenerated
	 */
	public Integer getOriTextId() {
		return oriTextId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diary_standard.ori_text_id
	 * @param oriTextId  the value for diary_standard.ori_text_id
	 * @mbggenerated
	 */
	public void setOriTextId(Integer oriTextId) {
		this.oriTextId = oriTextId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diary_standard.diary_date
	 * @return  the value of diary_standard.diary_date
	 * @mbggenerated
	 */
	public Date getDiaryDate() {
		return diaryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diary_standard.diary_date
	 * @param diaryDate  the value for diary_standard.diary_date
	 * @mbggenerated
	 */
	public void setDiaryDate(Date diaryDate) {
		this.diaryDate = diaryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diary_standard.start_time
	 * @return  the value of diary_standard.start_time
	 * @mbggenerated
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diary_standard.start_time
	 * @param startTime  the value for diary_standard.start_time
	 * @mbggenerated
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diary_standard.end_time
	 * @return  the value of diary_standard.end_time
	 * @mbggenerated
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diary_standard.end_time
	 * @param endTime  the value for diary_standard.end_time
	 * @mbggenerated
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diary_standard.action_addr
	 * @return  the value of diary_standard.action_addr
	 * @mbggenerated
	 */
	public String getActionAddr() {
		return actionAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diary_standard.action_addr
	 * @param actionAddr  the value for diary_standard.action_addr
	 * @mbggenerated
	 */
	public void setActionAddr(String actionAddr) {
		this.actionAddr = actionAddr == null ? null : actionAddr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diary_standard.action_state
	 * @return  the value of diary_standard.action_state
	 * @mbggenerated
	 */
	public String getActionState() {
		return actionState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diary_standard.action_state
	 * @param actionState  the value for diary_standard.action_state
	 * @mbggenerated
	 */
	public void setActionState(String actionState) {
		this.actionState = actionState == null ? null : actionState.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diary_standard.weather
	 * @return  the value of diary_standard.weather
	 * @mbggenerated
	 */
	public String getWeather() {
		return weather;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diary_standard.weather
	 * @param weather  the value for diary_standard.weather
	 * @mbggenerated
	 */
	public void setWeather(String weather) {
		this.weather = weather == null ? null : weather.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diary_standard.emotion
	 * @return  the value of diary_standard.emotion
	 * @mbggenerated
	 */
	public String getEmotion() {
		return emotion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diary_standard.emotion
	 * @param emotion  the value for diary_standard.emotion
	 * @mbggenerated
	 */
	public void setEmotion(String emotion) {
		this.emotion = emotion == null ? null : emotion.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column diary_standard.audio_location
	 * @return  the value of diary_standard.audio_location
	 * @mbggenerated
	 */
	public String getAudioLocation() {
		return audioLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column diary_standard.audio_location
	 * @param audioLocation  the value for diary_standard.audio_location
	 * @mbggenerated
	 */
	public void setAudioLocation(String audioLocation) {
		this.audioLocation = audioLocation == null ? null : audioLocation.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diary_standard
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", diaryCode=").append(diaryCode);
		sb.append(", oriTextId=").append(oriTextId);
		sb.append(", diaryDate=").append(diaryDate);
		sb.append(", startTime=").append(startTime);
		sb.append(", endTime=").append(endTime);
		sb.append(", actionAddr=").append(actionAddr);
		sb.append(", actionState=").append(actionState);
		sb.append(", weather=").append(weather);
		sb.append(", emotion=").append(emotion);
		sb.append(", audioLocation=").append(audioLocation);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diary_standard
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		DiaryStandard other = (DiaryStandard) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getDiaryCode() == null ? other.getDiaryCode() == null
						: this.getDiaryCode().equals(other.getDiaryCode()))
				&& (this.getOriTextId() == null ? other.getOriTextId() == null
						: this.getOriTextId().equals(other.getOriTextId()))
				&& (this.getDiaryDate() == null ? other.getDiaryDate() == null
						: this.getDiaryDate().equals(other.getDiaryDate()))
				&& (this.getStartTime() == null ? other.getStartTime() == null
						: this.getStartTime().equals(other.getStartTime()))
				&& (this.getEndTime() == null ? other.getEndTime() == null
						: this.getEndTime().equals(other.getEndTime()))
				&& (this.getActionAddr() == null ? other.getActionAddr() == null
						: this.getActionAddr().equals(other.getActionAddr()))
				&& (this.getActionState() == null ? other.getActionState() == null
						: this.getActionState().equals(other.getActionState()))
				&& (this.getWeather() == null ? other.getWeather() == null
						: this.getWeather().equals(other.getWeather()))
				&& (this.getEmotion() == null ? other.getEmotion() == null
						: this.getEmotion().equals(other.getEmotion()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getCreateBy() == null ? other.getCreateBy() == null
						: this.getCreateBy().equals(other.getCreateBy()))
				&& (this.getUpdateBy() == null ? other.getUpdateBy() == null
						: this.getUpdateBy().equals(other.getUpdateBy()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()))
				&& (this.getEnable() == null ? other.getEnable() == null : this.getEnable().equals(other.getEnable()))
				&& (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
				&& (this.getAudioLocation() == null ? other.getAudioLocation() == null
						: this.getAudioLocation().equals(other.getAudioLocation()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table diary_standard
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getDiaryCode() == null) ? 0 : getDiaryCode().hashCode());
		result = prime * result + ((getOriTextId() == null) ? 0 : getOriTextId().hashCode());
		result = prime * result + ((getDiaryDate() == null) ? 0 : getDiaryDate().hashCode());
		result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
		result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
		result = prime * result + ((getActionAddr() == null) ? 0 : getActionAddr().hashCode());
		result = prime * result + ((getActionState() == null) ? 0 : getActionState().hashCode());
		result = prime * result + ((getWeather() == null) ? 0 : getWeather().hashCode());
		result = prime * result + ((getEmotion() == null) ? 0 : getEmotion().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
		result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		result = prime * result + ((getEnable() == null) ? 0 : getEnable().hashCode());
		result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
		result = prime * result + ((getAudioLocation() == null) ? 0 : getAudioLocation().hashCode());
		return result;
	}

}